export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({ children }) {
 return (
    <html lang="en">
      <body>{children}
      <script src="https://unpkg.com/@googlemaps/js-api-loader@1.x/dist/index.min.js"></script></body>
    </html>
  )
}
